[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"


[build]
  functions = "netlify/functions"

[dev]
  publish = "dist"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200